{% set name = "pytest-timeout" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 7e68e90b01f9eff71332b25001f85c75495fc4e3a836701876183c4bcfd0540a

build:
  number: 0
  script: python -m pip install --no-deps --no-build-isolation --ignore-installed -vv .
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pytest >=7.0.0

test:
  requires:
    - pytest
    - pip
  imports:
    - pytest_timeout
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - py.test --help

about:
  home: https://github.com/pytest-dev/pytest-timeout
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This is a plugin which will terminate tests after a certain timeout.
  description: |
    pytest-timeout is a plugin which will terminate tests after a certain timeout.
    When doing so it will show a stack dump of all threads running at the time.
  doc_url: https://github.com/pytest-dev/pytest-timeout
  dev_url: https://github.com/pytest-dev/pytest-timeout

extra:
  recipe-maintainers:
    - flub
    - nicoddemus