{% set name = "pytest-timeout" %}
{% set version = "1.2.0" %}
{% set hash_type = "sha256" %}
{% set hash = "c29e3168f10897728059bd6b8ca20b28733d7fe6b8f6c09bb9d89f6146f27cb8" %}
{% set ext = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ ext }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pytest >=2.8.0

test:
  requires:
    - pytest
  imports:
    - pytest_timeout
  commands:
    - py.test --help

about:
  home: https://bitbucket.org/pytest-dev/pytest-timeout
  license: MIT
  license_file: LICENSE
  summary: This is a plugin which will terminate tests after a certain timeout.
  description: |
    pytest-timeout is a plugin which will terminate tests after a certain timeout.
    When doing so it will show a stack dump of all threads running at the time.
  doc_url: https://pypi.python.org/pypi/pytest-timeout
  dev_url: https://bitbucket.org/pytest-dev/pytest-timeout

extra:
  recipe-maintainers:
    - flub
    - nicoddemus
