{% set name = "pytest-timeout" %}
{% set version = "2.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 68c9d82dfe95fa65712e107010c9344e7d8b4afe8c975a7be0d273d939583a93

build:
  number: 0
  script: python -m pip install --no-deps --no-build-isolation --ignore-installed -vv .
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pytest >=8.4.0

test:
  requires:
    - pytest
    - pip
  imports:
    - pytest_timeout
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - py.test --help

about:
  home: https://github.com/pytest-dev/pytest-timeout
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This is a plugin which will terminate tests after a certain timeout.
  description: |
    pytest-timeout is a plugin which will terminate tests after a certain timeout.
    When doing so it will show a stack dump of all threads running at the time.
  doc_url: https://github.com/pytest-dev/pytest-timeout
  dev_url: https://github.com/pytest-dev/pytest-timeout

extra:
  recipe-maintainers:
    - flub
    - nicoddemus