travis:
  secure:
    BINSTAR_TOKEN: JC3/zZBFlLRwmDmsYwHpdtTOuf9V6VupL/tRGzrNnS0mRfzdSXMaz0yQxXLgbMaGjK5CCZVj0khFZG+4Igx2ctl+aYh9rp427Zhy+AGELBzaYpsheXjDQWUEDXDlQW4UvtSuTjz6k1cEV3aZe3bc75lAPtrU/lmkEmPQlYdZa605DaegmEdtpQ0OhCiWjwdq1cSAat2NnYSEkKUpGQUTi35nSeb3CYnjup6ijNSEwX4Xrob/sl7pIE1uALFnIYzSFYMmoXLjKStRgeiSdaLl1Q1lz+PpFBbMwaSaj822doBNxYKgkOejVdifvoBZiCa5Ai0Pa5qEaQbPAWeYC8ruitpVRVckHFCEjFDzO5IO5iLUUX2hTN+GRpKpOLU9OrTqvPdtwoBmc4+CZRMtlMX44X/sIIqPrHj4rgKaPB5jyWfbosc0IMlrSGbqv8i0LO7sl7GxXohV5DoybbZRoHwD526FQhMq8eWOZZdggI+oa2rk+lN4wgh0EDfKQ9w5vBy7SLbYOHwG+tIR0Atu6j1JQdPhZQhXbs2XpWzW4h/UeiCgqrdLsIlytiXwYmW5fTNq+Ab6C0EQLGks9zfO+TEdgBoPsR1iDd6McvEh3kLCPwz5um6wg9i45LxGyKdVN2yS6+lnBbgKb9Z5cs1N2YSfmYUwqTBfSlMBiLo/cZvOW/k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
