travis:
  secure:
    BINSTAR_TOKEN: uYGdoH8Hqiy+UN6p5yMj3EGyhfa/HAdncbfmBm3wxw0WrAEuGt6TgpSukNw62ADCMl+56UIFcNnGER/0WkEK/t8q+UgZ0oGHFlaAs5pmu6R5oXDnH5L+/YKZppIYnkapdiaxEyzwnKcJW9T7QhtRZbDrS3GNkOe8IlJnQzWDAei7U1HYGwfb3lUXNl8kZ8wkNhevxr9ke2a8qmsg/yHMM+/9Fma0Diz+f94dKHNcr4Qhf4x0H91bEFSnj4Dnl1Osxi4VuGQkJMtiuqdSAU+CLpqUx9XnObNUBIErOH5ygYlVwFBuVxaw/AkJX/bPfsR/KstmGpRw4k2nWenpKNRlddaGA0irZku97z58eXm6TMY3/7pkhIL/6Nvq2HzmhIuJiLKgCdF6NP9CXMnw2p8x7Kd2zls1UKQY9VemXu7Bg0sW5DFhEurqHNMqqxYLloi3CNfZeqEgOCxRAbNW//ntI9xicEjMjvf3gNqJGLLd6gavVVd126YvGldXigJcrNhaykKkz26jVpaOTwU8bBAoZ6SXM/UEVww7L0491by6wrpLkvc8fpTecbvxbj0iaPNs/MD3kUqWvcZw6qZ6E+q1nVSXEUodHbfihGmqhoshsjtoOxmP17CpJWqeXt3uU3jSxjvjzgxyJ3iLKAUJzJKCRDBoauuJqLZMfM461vqPit4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
