travis:
  secure:
    BINSTAR_TOKEN: dxT1/IpQc4JnJqTKkeUEAG0UUf6nyfK3MScK4r0ndESfK+l9E5hpMARI8XvKTNnnSs+ej5AGQTS8KrW+ighfmCt/Noa5rtm4CbKopEDtWc+6Zy7rs3zYpJUVJPUmxAXzwt9HGYLnIziJDxlDg9LQwDnIkdnbW2dbTbeaslK5HPMKasItf8K2ovis9NlppDphCi86PCbBO6ptpk4LmbCryZeax0VmCtV/um1AvhyvnF4d8VqdiEUoUWo4smsZ/cn81CsOMMUcWXqb6tRrLEEwzVnINmC2CUiK5BndAuxSDchf58jZRESw3yRxVB+dFbE8kwn8IIzOuQ5OxYPzRm5AYwNLFBj7zKo8y9op979QjZn+NdcUAd+S320Yo2zPRUgSxmxwl9tSc0JPqUq99/zqpFI6rt9hyfzicPuAMQcFBeeTIvYZGQvaaerMC13bD6xtredCA9AUVzsDaB2Npn3C/0sv1x89nlY7TjDekTZN9Z5Jzb59lbwH8bkgkSaYcin7NidewH0K84bTbx1cThZ5cbw5V9CJ1xBFfhl5sOAOoGl/2Wt+myignGCH0CuzuERLN6vySBPEh7sVNx8sxLBOnx2eC0d1/JAxWASJHFMIr6TNhqCzn72kkVcux8TpiT5+c9k1kWRWDCY7yOJargRtZ7DqzrfBZhdS/z3AGJKa9v4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
